modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/CMDCam/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="cmdcam"
    logoFile="cmdcam.png"
    version="2.1.1"
    displayName="CMDCam"
    displayURL="https://modrinth.com/mod/cmdcam"
    authors="CreativeMD"
    description='''Create camera paths.'''
    displayTest="NONE"

[[dependencies.cmdcam]]
    modId="neoforge"
    type="required"
    versionRange="[20.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmdcam]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmdcam]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.11.5,)"

[[mixins]]
   config="cmdcam.mixins.json"

